"""Add OTP fields

Revision ID: 0589dce81315
Revises: 
Create Date: 2026-03-23 11:21:34.298399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0589dce81315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('zone_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_code')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.alter_column('zone_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))

    # ### end Alembic commands ###
